[app]
port = 8989
session_name = "dws"
session_secret = "austiecodes"
aes_key = "shixiongzhenshuai"

[gpu]
enabled = true

[log]
info_log_file_path = "logs/info.log"
warning_log_file_path = "logs/warning.log"
error_log_file_path = "logs/error.log"

[pg]
host = "localhost"
port = "5432"
user = "yourusername"
password = "yourpassword"
db_name = "yourdatabase"
ssl_mode = "disable"
max_open_conns = 10
max_idle_conns = 5
conn_max_lifetime = 60

# dont need redis yet, but I'll keep it
[redis]
host = "localhost"
port = "6379"
password = ""
db = 0
pool_size = 10
dial_timeout = 5
read_timeout = 3
write_timeout = 3
conn_max_lifetime = 60

[mq]
protocol = "amqp"
host = "localhost"
port = 5672
username = "admin"
password = "password"
